In [1]:
import gdal
import time
import numpy as np
import random

In [2]:
infile = '/data/h5py_test/MOD13A1.A2006305.h17v07.006.2015161210823.hdf'

In [11]:
def load1(x,c):
    
    ysize = c // 2400
    
    for c1 in range(0,2400**2,c): 
        
        yoff = c1 // 2400
        
        ds = gdal.Open(x)
        sds_o = gdal.Open(ds.GetSubDatasets()[0][0])
    
        arr = sds_o.ReadAsArray(0,yoff,2400,ysize)
    
        ds = None
        sds_o = None
    
def load2(x,c):
    tt = []
    ysize = c//2400
    ds = gdal.Open(x)
    sds_o = gdal.Open(ds.GetSubDatasets()[0][0])
    
    for ii in range(10):
        
        t1 = time.time()
        
        for c1 in range(0,2400**2,c):
            
    
            yoff = c1 // 2400
        
            
    
            arr = sds_o.ReadAsArray(0,yoff,2400,ysize)
            
            print(arr)
            
    
        tt.append(time.time()- t1)
    
    ds = None
    sds_o = None
    
    return(tt)

In [4]:
chunks = [120*120,240*240,480*480,1200*1200,2400*2400]

In [5]:
t = []
ttemp = []
ttemp_archive = []

In [6]:
for c in chunks:
    
    for ix in range(10):
        
        t1 = time.time()
        
        load1(infile,c) 
        
        ttemp.append(time.time() - t1)
        
    t.append(np.mean(ttemp))
    
    print('Chunk {}: min = {}, max = {}, sd = {}'.format(c,np.min(ttemp),np.max(ttemp),np.std(ttemp)))
    
    
    ttemp = []
    
   
    

Chunk 14400: min = 48.8092520236969, max = 53.56500172615051, sd = 1.5509739809686138
Chunk 57600: min = 12.904799461364746, max = 14.060235261917114, sd = 0.37918789680294557
Chunk 230400: min = 3.3949711322784424, max = 3.8474953174591064, sd = 0.14221314195844026
Chunk 1440000: min = 0.6880881786346436, max = 0.9620232582092285, sd = 0.0703390885457462
Chunk 5760000: min = 0.3026292324066162, max = 0.3516833782196045, sd = 0.015709911936172626


In [12]:
for c in chunks:
    
           
    ttemp = load2(infile,c) 
        
    t.append(np.mean(ttemp))
    
    print('Chunk {}: min = {}, max = {}, sd = {}'.format(c,np.min(ttemp),np.max(ttemp),np.std(ttemp)))
    
    del ttemp

[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 [ 865  861  837 ... 1015  962  867]
 [ 858  860  865 ...  909  962  927]
 [ 871  871  874 ...  815  834  878]]
[[ 875  879  880 ...  823  831  882]
 [ 879  865  869 ...  819  842  885]
 [ 831  865  869 ...  889  889  879]
 [ 837  828  846 ...  953  903  858]
 [ 857  879  881 ...  932  945 1006]
 [ 887  874  861 ...  951  947  944]]
[[866 851 829 ... 948 969 979]
 [819 813 820 ... 932 942 966]
 [786 802 802 ... 932 923 977]
 [795 822 861 ... 953 953 895]
 [819 833 860 ... 965 964 964]
 [848 848 860 ... 965 964 964]]
[[ 839  848  847 ...  975  995 1004]
 [ 818  837  849 ...  984 1023 1018]
 [ 835  843  845 ... 1015 1029 1030]
 [ 829  832  823 ...  962  984  948]
 [ 802  813  819 ...  954  991  955]
 [ 805  827  843 ...  943  956  964]]
[[ 852  852  852 ...  929  920  962]
 [ 853  864  839 ... 1003  920  962]
 [ 877  892  899 ... 1003  987  984]
 [ 913  922  899 ... 1002 1016 10

[[5100 4386 4882 ... 3411 3363 3449]
 [4955 4729 4385 ... 3142 3467 2975]
 [4598 5505 4163 ... 3182 3347 2506]
 [4476 2775 2775 ... 3143 3119 2878]
 [3649 3088 3371 ... 3394 3119 2960]
 [4282 3527 3371 ... 3159 3159 2729]]
[[3756 3451 3168 ... 3194 2867 2867]
 [3034 3451 2939 ... 3337 2962 2229]
 [3862 3024 3104 ... 3288 2852 2602]
 [3240 3240 3537 ... 2940 3238 2397]
 [2907 3159 3833 ... 2962 3516 2877]
 [3391 4448 4125 ... 2452 2945 2922]]
[[3592 3561 3925 ... 2242 2558 3082]
 [4362 4142 4206 ... 3521 2558 3179]
 [4390 4639 4343 ... 3521 3140 3140]
 [3242 4335 4335 ... 2851 2970 2448]
 [4548 5065 4558 ... 2875 2813 2466]
 [5029 5065 5006 ... 2467 2657 2632]]
[[4385 5090 5061 ... 2250 2240 2362]
 [4385 4394 4660 ... 2082 1945 2220]
 [3241 3089 3961 ... 1994 1994 2189]
 [ 537 1267 3615 ... 3059 3079 2390]
 [-501 2569 4280 ... 3003 3238 3027]
 [-683 1946 3864 ... 2238 2789 2469]]
[[1875 3759 4633 ... 2527 2776 2809]
 [3671 4348 4633 ... 2707 2776 2486]
 [ 583 4348 3606 ... 3342 3342 245

[[2982 2328 2029 ... 1495 1228 1859]
 [1838 2287 2287 ... 2480 2081 1508]
 [2147 2152 2314 ... 2173 2081 1502]
 [1976 1676 1969 ... 2173 2173 2056]
 [1772 1736 1969 ... 1727 1823 1984]
 [1830 1736 2106 ... 1580 1393 1730]]
[[2245 2219 2490 ... 1991 1551 1406]
 [2383 2801 3184 ... 1623 1623 1431]
 [2764 3067 3179 ... 1647 1331 1426]
 [3063 3149 3153 ... 1271 1204 1575]
 [2841 2924 2884 ... 1268 1204 1248]
 [2808 2717 2640 ... 1644 1705 1289]]
[[2755 2431 2431 ... 1814 1705 1904]
 [2715 2743 2114 ... 1930 2268 2105]
 [2832 2743 1989 ... 1856 2188 2289]
 [3448 2183 2167 ... 1427 1427 1667]
 [2707 2045 2464 ... 1755 1778 1694]
 [3180 2476 1905 ... 2405 1775 1699]]
[[2746 3111 2700 ... 2495 1860 1710]
 [2136 2642 3043 ... 2035 3139 2289]
 [2265 2521 2636 ... 1669 2303 3191]
 [2508 2489 2200 ... 1725 1865 1948]
 [2241 2245 2245 ... 1705 1705 2474]
 [2287 2716 2861 ... 1472 1883 1883]]
[[2656 3122 2861 ... 1472 1469 1648]
 [2945 3122 3019 ... 1349 1441 1669]
 [2945 2855 2896 ... 1361 1311 145

 [2588 2588 2399 ... 2207 2141 2080]]
[[2596 2654 2339 ... 2342 2312 2312]
 [2671 2733 2339 ... 2418 2478 2398]
 [2759 2733 2469 ... 2396 2472 2574]
 [2974 3065 2601 ... 2701 2619 2538]
 [3124 3316 2935 ... 2393 2374 2300]
 [3230 3346 3193 ... 2305 2308 2393]]
[[2848 3127 2647 ... 2279 2308 2261]
 [3336 2815 3251 ... 1753 1753 1718]
 [2850 2710 2910 ... 2067 1691 1758]
 [3314 2623 2471 ... 2278 2063 1905]
 [2783 2431 2431 ... 2052 1778 2137]
 [2708 2630 3099 ... 2004 1793 1838]]
[[2869 2693 2898 ... 1947 1824 1833]
 [3357 3232 2898 ... 2063 1952 1971]
 [3062 3232 3284 ... 2124 2124 2127]
 [3062 3584 3380 ... 2185 2224 2037]
 [3675 3352 3352 ... 2278 2224 2230]
 [3556 3502 3321 ... 2278 2314 2246]]
[[3206 3666 3333 ... 2193 2224 2218]
 [3331 3727 3209 ... 2170 2174 2177]
 [2948 3180 3015 ... 2051 2060 1971]
 [2854 3513 2718 ... 1591 1700 1882]
 [2813 2834 2718 ... 1679 1908 2111]
 [2807 2834 3429 ... 1583 1654 1565]]
[[2371 2310 2963 ... 1610 1638 1635]
 [2349 2191 2749 ... 1701 1844 16

[[2479 2115 2410 ... 1525 1290 1381]
 [2194 2115 2364 ... 1403 1317 1356]
 [2194 2189 2242 ... 1257 1257 1271]
 [2302 2245 2544 ... 1094 1265 1265]
 [2720 2760 2760 ... 1094 1104 1122]
 [3052 3004 2770 ... 1076 1111 1197]]
[[3159 3012 2832 ... 1151 1107 1084]
 [2802 2916 3045 ... 1148 1288 1229]
 [2915 2763 3045 ... 1083 1359 1216]
 [3286 2763 3610 ... 1172 1265 1191]
 [3642 3407 3407 ... 1167 1167 1288]
 [3788 3358 3503 ... 1362 1330 1192]]
[[4239 4089 3551 ... 1233 1111 1262]
 [3930 3817 3854 ... 1270 1111 1064]
 [3892 4134 3871 ... 1270 1013  952]
 [3870 3426 3426 ... 1172  977  950]
 [3774 3101 2730 ... 1184 1046  982]
 [3220 2804 2391 ... 1082 1082  973]]
[[3243 3213 2980 ...  994 1227 1559]
 [3417 3278 2980 ... 1970 1653 1186]
 [2926 3146 2916 ... 1287 1142 1118]
 [2271 3146 3171 ... 1021 1086 1030]
 [2510 2608 2424 ... 1080 1080 1193]
 [2470 2061 2128 ...  873  968 1072]]
[[1995 1937 2065 ...  957  968  961]
 [2321 2318 2318 ...  957  908  997]
 [2284 2233 3110 ...  980  919 107

 [2338 2412 2562 ... 2231 2288 2356]]
[[2326 2603 2603 ... 2109 2216 2345]
 [3029 3092 2142 ... 2238 2302 2333]
 [2496 3092 2493 ... 2306 2371 2348]
 [2363 2595 2744 ... 2098 2161 2341]
 [2304 2792 2560 ... 2171 2161 2181]
 [2370 2399 2469 ... 2104 2191 2097]]
[[2607 2550 2265 ... 2104 1937 1746]
 [2718 2679 2393 ... 1761 1617 1666]
 [2381 2644 1982 ... 2237 1987 1626]
 [2757 2507 2102 ... 1848 1848 1884]
 [2612 2344 2344 ... 1915 1549 1468]
 [2271 2204 2410 ... 1849 1419 1441]]
[[2479 2115 2410 ... 1525 1290 1381]
 [2194 2115 2364 ... 1403 1317 1356]
 [2194 2189 2242 ... 1257 1257 1271]
 [2302 2245 2544 ... 1094 1265 1265]
 [2720 2760 2760 ... 1094 1104 1122]
 [3052 3004 2770 ... 1076 1111 1197]]
[[3159 3012 2832 ... 1151 1107 1084]
 [2802 2916 3045 ... 1148 1288 1229]
 [2915 2763 3045 ... 1083 1359 1216]
 [3286 2763 3610 ... 1172 1265 1191]
 [3642 3407 3407 ... 1167 1167 1288]
 [3788 3358 3503 ... 1362 1330 1192]]
[[4239 4089 3551 ... 1233 1111 1262]
 [3930 3817 3854 ... 1270 1111 10

[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [ 829  832  823 ...  962  984  948]
 [ 802  813  819 ...  954  991  955]
 [ 805  827  843 ...  943  956  964]]
[[ 852  852  852 ...  929  920  962]
 [ 853  864  839 ... 1003  920  962]
 [ 877  892  899 ... 1003  987  984]
 ...
 [ 862  845  861 ...  964  951  963]
 [ 848  840  844 ...  905  951  971]
 [ 842  840  828 ...  938  938  938]]
[[ 845  847  847 ...  952  969  968]
 [ 857  839  840 ...  967  976  989]
 [ 837  843  850 ...  980  983  980]
 ...
 [ 847  842  837 ... 1040 1086 1084]
 [ 858  866  877 ... 1015 1073 1080]
 [ 931  970  982 ... 1070 1051 1050]]
[[ 989  999  990 ... 1047 1010 1009]
 [ 983  984  956 ... 1023 1005 1019]
 [ 977  955  946 ...  951  951  973]
 ...
 [ 840  849  858 ...  999  999 1018]
 [ 878  879  858 ... 1021  999  997]
 [ 902  847  849 ...  980  994 1003]]
[[ 909  907  837 ...  983  988 1017]
 [ 898  889  844 ...  990 1000 1009]
 [ 860  838  8

[[7877 7949 7804 ... 4901 4728 4771]
 [7930 7981 7948 ... 4832 4832 4799]
 [8082 7907 7992 ... 4854 4594 4616]
 ...
 [7975 7748 7728 ... 4740 4721 5106]
 [7800 7748 5679 ... 4759 4745 5196]
 [7963 7963 7552 ... 4896 4896 5054]]
[[7744 8015 8094 ... 5063 5407 5564]
 [7944 7755 7841 ... 5112 5547 5613]
 [7627 7912 8115 ... 4807 5167 5613]
 ...
 [8306 8285 7502 ... 4971 5016 4713]
 [7203 7690 7567 ... 5426 4976 4705]
 [7605 7582 7582 ... 5751 5206 4705]]
[[7519 7653 7529 ... 5966 5206 4967]
 [7369 7531 7323 ... 5353 5589 5099]
 [7444 7486 7204 ... 5353 5527 5368]
 ...
 [7659 7726 7726 ... 4468 4766 4826]
 [7263 7726 7726 ... 4321 4601 4342]
 [7829 7857 7857 ... 4321 4535 4423]]
[[7665 7781 7781 ... 4800 4514 4325]
 [7781 7781 7781 ... 4546 4546 4088]
 [7706 7706 7450 ... 5065 4628 4562]
 ...
 [7642 7371 7576 ... 5070 6017 6422]
 [7477 7714 7794 ... 5673 5673 5591]
 [7629 7620 7779 ... 5295 4882 4964]]
[[7837 7499 7542 ... 4778 4725 4822]
 [7524 7467 7367 ... 4857 4834 5063]
 [7634 7716 72

 [5827 5302 6118 ... 3120 3322 3656]]
[[ 4452  5415  5304 ...  2131  3322  3391]
 [ 6002  5415  6189 ...  2334  3243  3898]
 [ 5854  6163  6002 ...  3034  3034  3687]
 ...
 [ 5620  6419  5500 ... -3000 -3000 -1449]
 [ 5620  5822  5553 ... -3000 -3000  -207]
 [ 6002  5672  5934 ...   353  -153  -153]]
[[4745 5347 5747 ... 3630 2414 -313]
 [4669 5780 6249 ... 3030 3521 1399]
 [4438 5934 6342 ... 3531 3882 2870]
 ...
 [6841 6841 6550 ... 3338 4099 4099]
 [6730 6913 6644 ... 3862 3774 3198]
 [6617 6930 6528 ... 3531 3364 3039]]
[[6735 7016 6591 ... 3538 3533 3358]
 [6701 6659 6591 ... 3215 3249 2809]
 [6712 6659 6866 ... 3044 3514 3225]
 ...
 [5493 5291 5903 ... 3251 3168 3121]
 [5252 5291 5710 ... 2894 3321 3368]
 [5252 4990 4983 ... 3246 2925 3068]]
[[5470 5617 5399 ... 3255 3484 3252]
 [5012 5377 5377 ... 3273 3484 3488]
 [4679 5216 5269 ... 3273 3323 3300]
 ...
 [5430 6204 6645 ... 3201 2861 2769]
 [6303 6352 6398 ... 3217 2976 2829]
 [6104 6429 6429 ... 3113 2943 2861]]
[[6479 6224 59

[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [ 840  849  858 ...  999  999 1018]
 [ 878  879  858 ... 1021  999  997]
 [ 902  847  849 ...  980  994 1003]]
[[ 909  907  837 ...  983  988 1017]
 [ 898  889  844 ...  990 1000 1009]
 [ 860  838  834 ... 1020 1020 1000]
 ...
 [1027 1030 1012 ...  998  975  970]
 [1046 1007 1019 ...  994  978  958]
 [1038 1003  985 ...  977  953  951]]
[[1027 1013 1012 ...  972  972  959]
 [1020 1041 1043 ...  977  976  976]
 [1043 1036 1043 ...  977  968  967]
 ...
 [1265 1237 1227 ...  955  945  889]
 [1275 1276 1272 ...  954  924  873]
 [1249 1283 1265 ...  915  880  861]]
[[1264 1286 1286 ...  893  899  909]
 [1228 1235 1244 ...  893  895  912]
 [1214 1219 1224 ...  937  913  913]
 ...
 [1281 1277  929 ...  933  820  831]
 [1281 1236 1048 ...  860  860  891]
 [1213 1287 1257 ...  875  924  803]]
[[1148 1113 1060 ...  891  859  908]
 [1174 1170 1260 ...  965  871  971]
 [1205 1104 11

[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [1404 1343 1382 ... 1539 1354  856]
 [1394 1351 1262 ... 2075 2196 1255]
 [1348 1289 1262 ... 2300 2196 1705]]
[[1343 1289 1175 ... 2300 1550 1090]
 [1333 1384 1213 ... 2504 1683 1185]
 [1244 1359 1327 ... 2801 1639 1113]
 ...
 [2271 3146 3171 ... 1021 1086 1030]
 [2510 2608 2424 ... 1080 1080 1193]
 [2470 2061 2128 ...  873  968 1072]]
[[ 1995  1937  2065 ...   957   968   961]
 [ 2321  2318  2318 ...   957   908   997]
 [ 2284  2233  3110 ...   980   919  1075]
 ...
 [ 5620  6419  5500 ... -3000 -3000 -1449]
 [ 5620  5822  5553 ... -3000 -3000  -207]
 [ 6002  5672  5934 ...   353  -153  -153]]
[[4745 5347 5747 ... 3630 2414 -313]
 [4669 5780 6249 ... 3030 3521 1399]
 [4438 5934 6342 ... 3531 3882 2870]
 ...
 [7849 7798 7762 ... 5437 5444 5618]
 [7832 7834 7824 ... 5427 5332 5669]
 [7889 7824 7824 ... 5119 5507 5637]]
[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  80

[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [7849 7798 7762 ... 5437 5444 5618]
 [7832 7834 7824 ... 5427 5332 5669]
 [7889 7824 7824 ... 5119 5507 5637]]
[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [7849 7798 7762 ... 5437 5444 5618]
 [7832 7834 7824 ... 5427 5332 5669]
 [7889 7824 7824 ... 5119 5507 5637]]
[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [7849 7798 7762 ... 5437 5444 5618]
 [7832 7834 7824 ... 5427 5332 5669]
 [7889 7824 7824 ... 5119 5507 5637]]
[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  846 ...  907  892  867]
 ...
 [7849 7798 7762 ... 5437 5444 5618]
 [7832 7834 7824 ... 5427 5332 5669]
 [7889 7824 7824 ... 5119 5507 5637]]
[[ 771  781  880 ... 1026 1048 1082]
 [ 776  776  803 ... 1328 1114  913]
 [ 849  859  8